### ISSUE TITLE
/usr/bin/python -> python3

### ISSUE THREAD

**Issue by wookietreiber** [jlc/vim-async-beans#3]
My current, up-to-date Arch Linux symlinks /usr/bin/python to python3 (actually 3.2.3 currently). This seems to be troublesome. I'm getting errors like the following, using envim (which uses vim-async-beans):

Traceback (most recent call last):
                                    File "/home/wookietreiber/.vim/vim-addons/vim-async-beans/python/VimProcRunner.py", line 573, in <module>
         ret = main()
                       File "/home/wookietreiber/.vim/vim-addons/vim-async-beans/python/VimProcRunner.py", line 549, in main
                                                                                                                                LogSetup().setup('', logfile)
                       File "/home/wookietreiber/.vim/vim-addons/vim-async-beans/python/LogBeans.py", line 42, in setup
                                                                                                                           self.initLogger(loggerName)
                File "/home/wookietreiber/.vim/vim-addons/vim-async-beans/python/LogBeans.py", line 65, in initLogger
                                                                                                                         if not self.handlers.has_key(name):
                    AttributeError: 'dict' object has no attribute 'has_key'

I don't know python much, but I think you can/should update all the python-script related stuff to use "/usr/bin/python2" instead of "/usr/bin/python".

**Comment by wookietreiber** [comment]
The following seems to work, although it does not fix the whole problem, because envim and propably other dependencies of it also use /usr/bin/python rather than /usr/bin/python2.

diff --git a/python/VimProcRunner.py b/python/VimProcRunner.py
index 35ae485..9a1082c 100755
--- a/python/VimProcRunner.py
+++ b/python/VimProcRunner.py
@@ -1,4 +1,4 @@
-#!/usr/bin/python
+#!/usr/bin/python2

 # VimProcRunner.py

diff --git a/test/TestPingProc.py b/test/TestPingProc.py
index 7a9e874..d9587d3 100755
--- a/test/TestPingProc.py
+++ b/test/TestPingProc.py
@@ -1,4 +1,4 @@
-#!/usr/bin/python
+#!/usr/bin/python2

 # Copyright 2012 Jeanluc Chasseriau jeanluc@lo.cx
 #
